In [ ]:
import torch, torchvision
from torch import nn

L1Loss function is simply calculating the difference for each elements, then sum.
![title](L1Loss.png)

In [17]:
loss = nn.L1Loss()
input = torch.randn((1, 1, 3, 5), requires_grad=True)
target = torch.randn((1,1, 3, 5), requires_grad=False)
print(input)
print(target)
output = loss(input, target)
print(output)

tensor([[[[-0.9994,  0.0977, -1.5567,  0.6818,  0.4399],
          [-0.5531,  1.4837,  0.4055,  0.0824,  0.5624],
          [-0.2537,  1.0333, -0.9199, -0.9975, -0.1293]]]], requires_grad=True)
tensor([[[[-0.1095, -1.4447,  0.8338, -1.6286, -0.5841],
          [ 0.6921, -1.6061, -0.5715,  1.5353,  0.7396],
          [ 1.2558,  0.0237, -1.3264,  1.8874,  1.0273]]]])
tensor(1.4711, grad_fn=<L1LossBackward0>)


![title](MSELoss.png)

In [21]:
loss = nn.MSELoss()
input = torch.randn((1, 1, 3, 5), requires_grad=True)
target = torch.randn((1,1, 3, 5), requires_grad=False)
print(input)
print(target)
output = loss(input, target)
print(output)


tensor([[[[ 0.0661,  0.6530,  0.6749, -0.9249,  0.2131],
          [-0.0283,  1.7550, -0.7082,  0.4015,  1.1674],
          [ 1.8761, -2.0933, -0.2760, -1.1823,  2.0525]]]], requires_grad=True)
tensor([[[[ 4.9823e-01, -1.5457e-01,  6.2111e-01,  1.0212e+00, -1.1143e+00],
          [-3.0439e+00,  7.8067e-01,  8.1989e-01, -4.6370e-01,  6.5458e-01],
          [ 1.1171e+00, -2.6876e-01, -5.4060e-01, -1.8342e-01, -5.8550e-04]]]])
tensor(1.9313, grad_fn=<MseLossBackward0>)


![title](CrossEntropyLoss.png)

In [24]:
# Example of target with class indices
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()

print(input)
print(target)
print(output)

tensor([[-0.0581, -1.0836,  0.3872, -1.1230,  0.7684],
        [ 0.2302,  0.7379,  1.5415,  0.4326,  0.7875],
        [-2.0927,  1.8935,  0.1923, -0.3023, -0.5047]], requires_grad=True)
tensor([1, 1, 2])
tensor(2.1687, grad_fn=<NllLossBackward0>)


In [25]:
# Example of target with class probabilities
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)
output = loss(input, target)
output.backward()

print(input)
print(target)
print(output)

tensor([[-0.9418,  0.9954, -0.9764, -0.0709, -1.9676],
        [ 0.9393,  0.8574, -1.4145, -0.9547, -0.0051],
        [ 0.6298,  0.0848, -0.1890,  1.1781,  0.9910]], requires_grad=True)
tensor([[0.2293, 0.0312, 0.0355, 0.1382, 0.5658],
        [0.0218, 0.1648, 0.3926, 0.3720, 0.0488],
        [0.0806, 0.0376, 0.1159, 0.2068, 0.5591]])
tensor(2.3096, grad_fn=<DivBackward1>)


See Other examples for better understanding how to use the loss function 